title: Roberto Aldaz Corona
description: Bienvenido/a a mi portafolio de análisis de datos: donde los números cuentan historias.
show_downloads: True
remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme
